name: pt_tracker
description: "A minimal Todo app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_animate: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
  - assets/sounds/
  - assets/animations/
  fonts:
  - family: Mukta
    fonts:
    - asset: assets/fonts/Mukta-Regular.ttf
    - asset: assets/fonts/Mukta-Light.ttf
      weight: 300
    - asset: assets/fonts/Mukta-Medium.ttf
      weight: 500
    - asset: assets/fonts/Mukta-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/Mukta-Bold.ttf
      weight: 700
